import AppBar from '@components/Appbar'
import SessionProvider from '@context/SessionProvider'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'
import { options } from './api/auth/[...nextauth]/options'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <AppBar />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
