import AppBar from '@components/Appbar'
import Providers from '@providers'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'
import { options } from './api/auth/[...nextauth]/options'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = { children: React.ReactNode }

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(options)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <AppBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
