name: Continuous integration
run-name: Run tests and build

on:
    push:
        branches:
            - feature/*

jobs:
    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v3

    #         - name: Install node modules
    #           run: yarn

    #         - name: Run test with jest
    #           run: yarn run test

    build:
        runs-on: ubuntu-latest
        # needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install node modules
              run: yarn

            - name: Build
              run: yarn build
