name: Continuous integration

on:
    push:
        branches:
            - feature/*

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install node modules
              run: yarn

            - name: Run test with jest
              run: yarn run test
